#!/bin/bash
set -e

# Colors for better output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=======================================${NC}"
echo -e "${BLUE}Ninja Punk Girls NFT Vercel Deployment${NC}"
echo -e "${BLUE}=======================================${NC}"
echo ""

# Check if required tools are installed
echo -e "${YELLOW}Checking for required tools...${NC}"

if ! command -v git &> /dev/null; then
    echo -e "${RED}Error: git is not installed.${NC}"
    exit 1
fi

if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Error: python3 is not installed.${NC}"
    exit 1
fi

echo -e "${GREEN}All required tools are installed!${NC}"
echo ""

# Prepare the project
echo -e "${YELLOW}Preparing project for deployment...${NC}"

# Create required directories
mkdir -p output
mkdir -p api

# Make scripts executable
chmod +x build.py
if [ -f prepare-vercel.sh ]; then
    chmod +x prepare-vercel.sh
fi

# Set up virtual environment if not already created
if [ ! -d "venv" ]; then
    echo -e "${YELLOW}Creating virtual environment...${NC}"
    python3 -m venv venv
fi

# Activate virtual environment
echo -e "${YELLOW}Activating virtual environment...${NC}"
source venv/bin/activate

# Install dependencies
echo -e "${YELLOW}Installing required dependencies...${NC}"
python3 -m pip install -r requirements.txt || { echo -e "${RED}Failed to install dependencies${NC}"; exit 1; }

# Generate the NFT Studio HTML
echo -e "${YELLOW}Generating NFT Studio HTML...${NC}"
python3 build.py || { echo -e "${RED}Failed to generate HTML${NC}"; exit 1; }

# Create empty nft_studio.html to ensure it's in git
if [ ! -f nft_studio.html ]; then
    echo "<!-- This file will be generated by build.py during deployment -->" > nft_studio.html
fi

# Check if we're on vercel
if [ -n "$VERCEL" ] && [ "$VERCEL" = "1" ]; then
    echo -e "${GREEN}Running on Vercel! Deployment will be handled automatically.${NC}"
    exit 0
fi

# Local testing section
echo -e "${YELLOW}Running local server for testing...${NC}"
echo -e "${GREEN}You can access the NFT Studio at:${NC}"
echo -e "${BLUE}http://localhost:8080${NC}"
echo -e "${YELLOW}Press Ctrl+C to stop the server.${NC}"

# Kill any running Python http servers
pkill -f "python3 -m http.server" || true

# Deactivate virtual environment before starting server 
# (http.server doesn't need the venv)
deactivate

# Start a local server
python3 -m http.server 8080 