#!/bin/bash

echo "Preparing project for Vercel deployment..."

# Make sure output directory exists
mkdir -p output

# Make sure API directory exists
mkdir -p api

# Create .gitkeep file for output directory if it doesn't exist
if [ ! -f output/.gitkeep ]; then
  echo "# Keep this directory in git" > output/.gitkeep
fi

# Make sure build.py is executable
chmod +x build.py

# Create empty nft_studio.html to ensure it's in git
if [ ! -f nft_studio.html ]; then
  echo "<!-- This file will be generated by build.py during deployment -->" > nft_studio.html
fi

echo "Project preparation complete!"
echo "You can now deploy to Vercel by linking your GitHub repository."
echo "Make sure to set the following in your Vercel project settings:"
echo "- Build Command: python build.py"
echo "- Output Directory: output"
echo "- Install Command: pip install -r requirements.txt"
echo "Enjoy your Ninja Punk Girls NFT Studio!" 